title: Site

columns:
  - width: 1/2
    fields:
      events:
        label: Events
        type: structure
        fields:
          name:
            label: Name
            type: text
          description:
            label: Description
            type: text
          start_datetime:
            label: Start Time
            type: date
          end_datetime:
            label: End Time
            type: date
            time: true
            step: 15
          modality:
            type: text
          ceus:
            type: text
          archive:
            type: text
