title: Site

tabs:
  info:
    label: Additional info
    icon: twitter
    columns:
      - width: 1/2
        fields:
          copyright:
            type: text
          facebook:
            label: Facebook
            type: url
            icon: facebook
          twitter:
            label: Twitter
            type: text
            icon: twitter
            placeholder: @username
          instagram:
            label: Instagram
            type: text
            icon: instagram
            placeholder: username
          linkedin:
            label: LinkedIn
            type: text
            icon: linkedin
            placeholder: username
          vimeo:
            label: Vimeo
            type: text
            icon: vimeo
            placeholder: username
      - width: 1/2
        sections:
          pages:
            type: pages
            status: listed
          notes: sections/notes
          info:
            type: fields
            fields:
              website:
                label: Website
                type: url
                width: 1/2
              bio:
                label: Bio
                type: textarea

  address:
    label: Address
    icon: text
    sections:
      address:
        type: fields
        fields:
          street:
            label: Street
            type: text
          zip:
            label: ZIP
            type: text
            width: 1/4
          city:
            label: City
            type: text
            width: 3/4
          country:
            label: Country
            type: text
